### ISSUE TITLE
Ampoule 0.1 does not work on Windows XP

### ISSUE THREAD

**Issue by moshez** [twisted/ampoule#4]
Hello,

I am trying to run Ampoule on windows. On my windows XP (SP3) machine I got the following error when trying to run the examples:

        Traceback (most recent call last):
          File "c:\python25\lib\site-packages\twisted\internet\defer.py", line 7
37, in _inlineCallbacks
            result = g.send(result)
          File "C:\Documents and Settings\dia\Desktop\ampoule-0.1\examples\pid.p
y", line 25, in _run
            yield pp.start()
          File "c:\python25\lib\site-packages\ampoule-0.1-py2.5.egg\ampoule\pool
.py", line 97, in start
            return self.adjustPoolSize()
          File "c:\python25\lib\site-packages\twisted\internet\defer.py", line 8
22, in unwindGenerator
            return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
        --- <exception caught here> ---
          File "c:\python25\lib\site-packages\twisted\internet\defer.py", line 7
37, in _inlineCallbacks
            result = g.send(result)
          File "c:\python25\lib\site-packages\ampoule-0.1-py2.5.egg\ampoule\pool.py", line 358, in adjustPoolSize
            self.startAWorker()
          File "c:\python25\lib\site-packages\ampoule-0.1-py2.5.egg\ampoule\pool.py", line 192, in startAWorker
            ampParent=self.ampParent)
          File "c:\python25\lib\site-packages\ampoule-0.1-py2.5.egg\ampoule\main.py", line 212, in startAMPProcess
            return self.startPythonProcess(prot, self.childReactor, fullPath)
          File "c:\python25\lib\site-packages\ampoule-0.1-py2.5.egg\ampoule\main.py", line 228, in startPythonProcess
            usePTY=self.usePTY, packages=self.packages)
          File "c:\python25\lib\site-packages\ampoule-0.1-py2.5.egg\ampoule\main.py", line 260, in spawnProcess
            childFDs={0:"w", 1:"r", 2:"r", 3:"w", 4:"r"})
          File "c:\python25\lib\site-packages\twisted\internet\posixbase.py", line 231, in spawnProcess
            raise ValueError("Customizing childFDs is not supported on Windows.")
        exceptions.ValueError: Customizing childFDs is not supported on Windows.

Any help is appreciated.

**Comment by glyph** [comment]
python 2.5 is end of lifed, so is windows XP. probably not going to address this ;)
